package cli

import (
	"os"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func writeTestFile(t *testing.T, path, content string) {
	t.Helper()
	require.NoError(t, os.WriteFile(path, []byte(content), 0o644))
}

func readTestFile(t *testing.T, path string) string {
	t.Helper()

	data, err := os.ReadFile(path)
	require.NoError(t, err)

	return string(data)
}

const sandboxImageTestConfig = `# panda configuration
# Generated by 'panda init'.

server:
  host: "0.0.0.0"
  port: 2480

sandbox:
  image: "ethpandaops/panda:sandbox-latest"
  network: "ethpandaops-panda-internal"

proxy:
  url: "https://panda-proxy.ethpandaops.io"
`

func TestRewriteSandboxImagePinsFloatingTag(t *testing.T) {
	t.Parallel()

	updated, outcome, current := rewriteSandboxImage(sandboxImageTestConfig, "ethpandaops/panda:sandbox-0.33.0")

	assert.Equal(t, sandboxPinUpdated, outcome)
	assert.Equal(t, "ethpandaops/panda:sandbox-latest", current)
	assert.Contains(t, updated, `  image: "ethpandaops/panda:sandbox-0.33.0"`)
	assert.NotContains(t, updated, "sandbox-latest")

	// Everything else is untouched.
	assert.Contains(t, updated, `# Generated by 'panda init'.`)
	assert.Contains(t, updated, `  network: "ethpandaops-panda-internal"`)
	assert.Contains(t, updated, `  url: "https://panda-proxy.ethpandaops.io"`)
}

func TestRewriteSandboxImageUpdatesOldPin(t *testing.T) {
	t.Parallel()

	doc := strings.ReplaceAll(sandboxImageTestConfig, "sandbox-latest", "sandbox-0.32.0")

	updated, outcome, current := rewriteSandboxImage(doc, "ethpandaops/panda:sandbox-0.33.0-rc.3")

	assert.Equal(t, sandboxPinUpdated, outcome)
	assert.Equal(t, "ethpandaops/panda:sandbox-0.32.0", current)
	assert.Contains(t, updated, `  image: "ethpandaops/panda:sandbox-0.33.0-rc.3"`)
}

func TestRewriteSandboxImageAlreadyPinned(t *testing.T) {
	t.Parallel()

	doc := strings.ReplaceAll(sandboxImageTestConfig, "sandbox-latest", "sandbox-0.33.0")

	updated, outcome, current := rewriteSandboxImage(doc, "ethpandaops/panda:sandbox-0.33.0")

	assert.Equal(t, sandboxPinAlreadyPinned, outcome)
	assert.Equal(t, "ethpandaops/panda:sandbox-0.33.0", current)
	assert.Equal(t, doc, updated)
}

func TestRewriteSandboxImageLeavesCustomImages(t *testing.T) {
	t.Parallel()

	for name, image := range map[string]string{
		"local build":    "ethpandaops-panda-sandbox:latest",
		"other repo":     "ghcr.io/example/sandbox:1.0",
		"non-sandbox":    "ethpandaops/panda:server-0.33.0",
		"content hashed": "ghcr.io/ethpandaops/panda-sandbox:d94be7356ab9d3ce",
	} {
		doc := strings.ReplaceAll(sandboxImageTestConfig, "ethpandaops/panda:sandbox-latest", image)

		updated, outcome, current := rewriteSandboxImage(doc, "ethpandaops/panda:sandbox-0.33.0")

		assert.Equal(t, sandboxPinCustomImage, outcome, "%s should be left alone", name)
		assert.Equal(t, image, current, name)
		assert.Equal(t, doc, updated, name)
	}
}

func TestRewriteSandboxImageOnlyTouchesSandboxBlock(t *testing.T) {
	t.Parallel()

	doc := `other:
  image: "ethpandaops/panda:sandbox-latest"

sandbox:
  image: "ethpandaops/panda:sandbox-latest"
`

	updated, outcome, _ := rewriteSandboxImage(doc, "ethpandaops/panda:sandbox-0.33.0")

	assert.Equal(t, sandboxPinUpdated, outcome)
	assert.Contains(t, updated, "other:\n  image: \"ethpandaops/panda:sandbox-latest\"")
	assert.Contains(t, updated, "sandbox:\n  image: \"ethpandaops/panda:sandbox-0.33.0\"")
}

func TestRewriteSandboxImagePreservesCommentAndStyle(t *testing.T) {
	t.Parallel()

	doc := "sandbox:\n  image: ethpandaops/panda:sandbox-latest # keep me\n"

	updated, outcome, _ := rewriteSandboxImage(doc, "ethpandaops/panda:sandbox-0.33.0")

	assert.Equal(t, sandboxPinUpdated, outcome)
	assert.Contains(t, updated, `  image: "ethpandaops/panda:sandbox-0.33.0" # keep me`)
}

func TestRewriteSandboxImageNoSandboxBlock(t *testing.T) {
	t.Parallel()

	doc := "server:\n  port: 2480\n"

	updated, outcome, _ := rewriteSandboxImage(doc, "ethpandaops/panda:sandbox-0.33.0")

	assert.Equal(t, sandboxPinNotApplicable, outcome)
	assert.Equal(t, doc, updated)
}

func TestPinSandboxImageInConfigEndToEnd(t *testing.T) {
	dir := t.TempDir()
	composeFile = dir + "/docker-compose.yaml"

	t.Cleanup(func() { composeFile = "" })

	configPath := dir + "/config.yaml"
	writeTestFile(t, configPath, sandboxImageTestConfig)

	// Dry run reports the change without writing.
	outcome, current, err := pinSandboxImageInConfig("v0.33.0", true)
	assert.NoError(t, err)
	assert.Equal(t, sandboxPinUpdated, outcome)
	assert.Equal(t, "ethpandaops/panda:sandbox-latest", current)
	assert.Contains(t, readTestFile(t, configPath), "sandbox-latest")

	// Real run rewrites the file.
	outcome, _, err = pinSandboxImageInConfig("v0.33.0", false)
	assert.NoError(t, err)
	assert.Equal(t, sandboxPinUpdated, outcome)
	assert.Contains(t, readTestFile(t, configPath), `image: "ethpandaops/panda:sandbox-0.33.0"`)

	// Second run is a no-op.
	outcome, _, err = pinSandboxImageInConfig("v0.33.0", false)
	assert.NoError(t, err)
	assert.Equal(t, sandboxPinAlreadyPinned, outcome)
}

func TestPinSandboxImageInConfigDevBuildSkips(t *testing.T) {
	dir := t.TempDir()
	composeFile = dir + "/docker-compose.yaml"

	t.Cleanup(func() { composeFile = "" })

	configPath := dir + "/config.yaml"
	writeTestFile(t, configPath, sandboxImageTestConfig)

	// "dev" has no published sandbox image; the config must not be rewritten
	// (it would replace a concrete pin with a floating tag on dev builds).
	outcome, _, err := pinSandboxImageInConfig("dev", false)
	assert.NoError(t, err)
	assert.Equal(t, sandboxPinNotApplicable, outcome)
	assert.Contains(t, readTestFile(t, configPath), "sandbox-latest")
}

func TestPinSandboxImageInConfigMissingFile(t *testing.T) {
	dir := t.TempDir()
	composeFile = dir + "/docker-compose.yaml"

	t.Cleanup(func() { composeFile = "" })

	outcome, _, err := pinSandboxImageInConfig("v0.33.0", false)
	assert.NoError(t, err)
	assert.Equal(t, sandboxPinNotApplicable, outcome)
}
